blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/alshedivat/al-folio/discussions/categories/q-a
    about: Ask and answer al-folio related questions.
  - name: ğŸ“– Read the documentation
<<<<<<< HEAD
    url: https://github.com/alshedivat/al-folio/blob/main/README.md
=======
    url: https://github.com/alshedivat/al-folio/blob/master/README.md
>>>>>>> c8e91b7a (Initial commit)
    about: Please consult the documentation before opening any issues!
